# Generated by Django 5.2.8 on 2025-11-28 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp_created', models.FloatField()),
                ('timestamp_modified', models.FloatField()),
            ],
            options={
                'db_table': 'contexts',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('machine_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('last_sync', models.FloatField(blank=True, null=True)),
                ('timestamp_created', models.FloatField()),
                ('is_active', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'machines',
            },
        ),
        migrations.CreateModel(
            name='SyncMetadata',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('timestamp_updated', models.FloatField()),
            ],
            options={
                'db_table': 'sync_metadata',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('kind', models.CharField(max_length=50)),
                ('timestamp_created', models.FloatField()),
                ('timestamp_modified', models.FloatField()),
                ('is_dirty', models.IntegerField(default=1)),
                ('deleted_at', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('context', models.ForeignKey(blank=True, db_column='context', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tjai_app.context')),
                ('parent', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='tjai_app.entry')),
            ],
            options={
                'db_table': 'entries',
            },
        ),
        migrations.CreateModel(
            name='SubNote',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('timestamp_created', models.FloatField()),
                ('data', models.JSONField(blank=True, null=True)),
                ('parent', models.ForeignKey(db_column='parent_id', on_delete=django.db.models.deletion.CASCADE, related_name='sub_notes', to='tjai_app.entry')),
            ],
            options={
                'db_table': 'sub_notes',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=255)),
                ('entry', models.ForeignKey(db_column='entry_id', on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='tjai_app.entry')),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.UniqueConstraint(condition=models.Q(('name__isnull', False)), fields=('context', 'name'), name='unique_context_name'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['tag_name'], name='idx_tags_tag_name'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('tag_name', 'entry'), name='unique_tag_entry'),
        ),
    ]
