# Generated by Django 5.2.8 on 2026-01-17 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tjai_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysConfig',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp_modified', models.FloatField()),
            ],
            options={
                'db_table': 'sysconfig',
            },
        ),
    ]
