# Generated by Django 5.2.8 on 2026-02-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tjai_app', '0002_sysconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagStats',
            fields=[
                ('tag_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('entry_count', models.IntegerField(default=0)),
                ('is_context_only', models.BooleanField(default=False)),
                ('only_context', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.FloatField()),
            ],
            options={
                'db_table': 'tag_stats',
            },
        ),
    ]
