# Generated by Django 5.2.8 on 2026-02-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tjai_app', '0003_tagstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='mmdd',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
