# Generated by Django 5.2.8 on 2026-02-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tjai_app', '0004_entry_mmdd'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, max_length=100)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('level', models.IntegerField(choices=[(50, 'CRITICAL'), (40, 'ERROR'), (30, 'WARNING'), (20, 'INFO'), (10, 'DEBUG')], db_index=True, default=20)),
                ('levelname', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('extra_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'applog',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'source'], name='applog_timesta_42e4bd_idx')],
            },
        ),
    ]
