# Generated by Django 5.2.8 on 2026-02-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tjai_app', '0005_applog'),
    ]

    operations = [
        migrations.CreateModel(
            name='RssItem',
            fields=[
                ('guid', models.TextField(primary_key=True, serialize=False)),
                ('feed_url', models.TextField()),
                ('source', models.TextField()),
                ('category', models.TextField(default='uncategorized')),
                ('title', models.TextField()),
                ('url', models.TextField()),
                ('precis', models.TextField(default='')),
                ('published', models.DateTimeField(null=True)),
                ('fetched', models.DateTimeField()),
                ('read', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'db_table': 'rss_items',
                'indexes': [models.Index(fields=['read', 'category', 'source'], name='rss_items_read_1627a1_idx')],
            },
        ),
    ]
