# Generated by Django 5.2.8 on 2026-03-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tjai_app', '0006_add_rssitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssitem',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
