# Generated by Django 5.2.8 on 2026-03-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tjai_app', '0007_add_rssitem_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
