# Generated by Django 5.2.8 on 2026-03-04 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tjai_app', '0008_add_context_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('relation_type', models.CharField(max_length=255)),
                ('data', models.JSONField(blank=True, null=True)),
                ('timestamp_created', models.FloatField()),
                ('timestamp_modified', models.FloatField()),
                ('entry1', models.ForeignKey(db_column='entry1_id', on_delete=django.db.models.deletion.CASCADE, related_name='relations_as_entry1', to='tjai_app.entry')),
                ('entry2', models.ForeignKey(db_column='entry2_id', on_delete=django.db.models.deletion.CASCADE, related_name='relations_as_entry2', to='tjai_app.entry')),
            ],
            options={
                'db_table': 'relations',
                'indexes': [models.Index(fields=['entry1'], name='idx_relations_entry1'), models.Index(fields=['entry2'], name='idx_relations_entry2')],
                'constraints': [models.UniqueConstraint(fields=('entry1', 'entry2'), name='unique_relation_pair'), models.CheckConstraint(condition=models.Q(('entry1', models.F('entry2')), _negated=True), name='no_self_relation')],
            },
        ),
    ]
