# Generated by Django 5.2.8 on 2026-03-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tjai_app', '0009_add_relation_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='KozyChat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sender', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'kozy_chat',
                'ordering': ['timestamp'],
            },
        ),
    ]
