# Generated by Django 5.2.8 on 2026-03-19 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tjai_app', '0010_kozy_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('data', models.JSONField(blank=True, null=True)),
                ('changed_by', models.CharField(default='unknown', max_length=100)),
                ('timestamp', models.FloatField()),
                ('entry', models.ForeignKey(db_column='entry_id', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='tjai_app.entry')),
            ],
            options={
                'db_table': 'entry_versions',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['entry', '-timestamp'], name='idx_entryver_entry_ts')],
            },
        ),
    ]
