# Generated by Django 5.2.8 on 2026-03-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tjai_app', '0011_entry_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryversion',
            name='version_num',
            field=models.IntegerField(default=0),
        ),
    ]
