# Generated by Django 5.2.8 on 2026-03-23 13:13
# Customized: adds GIN index, database trigger for auto-update, and backfill

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tjai_app', '0012_entry_version_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        # GIN index for fast full-text search
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS entries_search_gin ON entries USING GIN (search_vector);",
            reverse_sql="DROP INDEX IF EXISTS entries_search_gin;",
        ),
        # Database trigger: auto-update search_vector on insert or content update
        migrations.RunSQL(
            sql="""
                CREATE OR REPLACE FUNCTION entries_search_vector_update() RETURNS trigger AS $$
                BEGIN
                    NEW.search_vector := to_tsvector('english', COALESCE(NEW.content, ''));
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                DROP TRIGGER IF EXISTS entries_search_vector_trigger ON entries;
                CREATE TRIGGER entries_search_vector_trigger
                    BEFORE INSERT OR UPDATE OF content ON entries
                    FOR EACH ROW
                    EXECUTE FUNCTION entries_search_vector_update();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS entries_search_vector_trigger ON entries;
                DROP FUNCTION IF EXISTS entries_search_vector_update();
            """,
        ),
        # Backfill all existing entries
        migrations.RunSQL(
            sql="UPDATE entries SET search_vector = to_tsvector('english', COALESCE(content, ''));",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
