# Generated by Django 5.2.8 on 2026-03-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tjai_app', '0013_add_search_vector'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['search_vector'], name='entries_search_gin'),
        ),
    ]
