# Generated by Django 6.0.5 on 2026-08-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tjai_app', '0019_entries_todo_bangs_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('first_seen', models.DateTimeField()),
                ('source', models.TextField()),
                ('severity', models.TextField(default='info')),
                ('title', models.TextField()),
                ('url', models.TextField(default='')),
                ('was_read', models.BooleanField(db_index=True, default=False)),
                ('archived', models.BooleanField(db_index=True, default=False)),
                ('dedup_key', models.TextField(db_index=True, default='')),
                ('count', models.IntegerField(default=1)),
                ('data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'capcom_notices',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['archived', 'was_read'], name='capcom_noti_archive_16aab1_idx'), models.Index(fields=['source', '-timestamp'], name='capcom_noti_source_c8fbc4_idx')],
            },
        ),
    ]
