# Generated by Django 6.0.3 on 2026-09-12 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tjai_app', '0025_search_vector_slash_normalize'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMSession',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('native_id', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=160)),
                ('host', models.CharField(max_length=160)),
                ('client', models.CharField(max_length=80)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('cwd', models.TextField(blank=True)),
                ('resources', models.JSONField(default=list)),
                ('delivery', models.CharField(default='pull', max_length=40)),
                ('state', models.CharField(default='idle', max_length=20)),
                ('last_seen', models.DateTimeField()),
            ],
            options={
                'db_table': 'llm_sessions',
                'indexes': [models.Index(fields=['last_seen'], name='llm_sessions_seen')],
            },
        ),
        migrations.CreateModel(
            name='LLMMessage',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('sender_snapshot', models.JSONField(default=dict)),
                ('content', models.TextField()),
                ('resource', models.CharField(blank=True, max_length=160)),
                ('reply_requested', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tjai_app.llmmessage')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_messages', to='tjai_app.llmsession')),
            ],
            options={
                'db_table': 'llm_messages',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LLMDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='pending', max_length=32)),
                ('updated_at', models.DateTimeField()),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('detail', models.TextField(blank=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='tjai_app.llmmessage')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbox', to='tjai_app.llmsession')),
            ],
            options={
                'db_table': 'llm_deliveries',
                'indexes': [models.Index(fields=['recipient', 'state'], name='llm_inbox_state')],
                'constraints': [models.UniqueConstraint(fields=('message', 'recipient'), name='llm_delivery_recipient')],
            },
        ),
    ]
