# Generated by Django 6.0.5 on 2026-10-10 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tjai_app', '0026_llm_communications'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthClient',
            fields=[
                ('client_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('info', models.JSONField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'oauth_clients',
            },
        ),
        migrations.CreateModel(
            name='OAuthGrant',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('params', models.JSONField()),
                ('status', models.CharField(default='pending', max_length=10)),
                ('code_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('code_expires_at', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grants', to='tjai_app.oauthclient')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'oauth_grants',
            },
        ),
        migrations.CreateModel(
            name='OAuthToken',
            fields=[
                ('token_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=10)),
                ('scopes', models.JSONField(default=list)),
                ('resource', models.CharField(max_length=255)),
                ('expires_at', models.FloatField()),
                ('revoked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tokens', to='tjai_app.oauthgrant')),
            ],
            options={
                'db_table': 'oauth_tokens',
            },
        ),
    ]
