from django.contrib import admin
from django.urls import path, include

from tjai_app import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("mcp/", include("mcp_server.urls")),
    path("mcp", include("mcp_server.urls")),  # Also handle without trailing slash
    path("api/health", views.api_health, name="api_health"),
    path("api/sync/push", views.sync_push, name="sync_push"),
    path("api/sync/pull", views.sync_pull, name="sync_pull"),
    path("api/worker/poll", views.worker_poll, name="worker_poll"),
    path("api/worker/result", views.worker_result, name="worker_result"),
    path("api/work/submit", views.api_work_submit, name="api_work_submit"),
    path("api/work/result/<uuid:entry_uuid>", views.api_work_result,
         name="api_work_result"),
    path("api/command", views.api_command, name="api_command"),
    path("api/entry/create", views.api_entry_create, name="api_entry_create"),
    path("api/diary/today", views.api_diary_today, name="api_diary_today"),
    path("api/entry/<str:entry_id>", views.api_delete_entry, name="api_delete_entry"),
    path("api/add-journal", views.api_add_journal, name="api_add_journal"),
    path("api/add-bookmark", views.api_add_bookmark, name="api_add_bookmark"),
    path("api/log", views.api_log, name="api_log"),
    path("api/add-entry", views.api_add_entry, name="api_add_entry"),
    path("api/dialog", views.api_dialog, name="api_dialog"),
    path("api/dialog/daily-counts", views.api_dialog_daily_counts, name="api_dialog_daily_counts"),
    path("api/kozy-chat", views.api_kozy_chat, name="api_kozy_chat"),
    path("api/bulk-import", views.api_bulk_import, name="api_bulk_import"),
    # Public landing
    path("", views.public_home, name="public_home"),
    # Login/Logout
    path("auto-login", views.auto_login, name="auto_login"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    # Dashboard (protected by login)
    path("dashboard/", views.dashboard, name="dashboard"),
    path("diary/", views.diary_page, name="diary_page"),
    path("versions/", views.versions_page, name="versions_page"),
    path("api/diary/entries", views.api_diary_entries, name="api_diary_entries"),
    path("api/dashboard/calendar", views.dashboard_calendar, name="dashboard_calendar"),
    path("api/dashboard/status", views.dashboard_status, name="dashboard_status"),
    path("api/dashboard/search", views.dashboard_search, name="dashboard_search"),
    path("api/dashboard/named", views.dashboard_named, name="dashboard_named"),
    path("synopsis/", views.daily_synopsis, name="daily_synopsis"),
    path("api/synopsis/dates", views.daily_synopsis_data, name="daily_synopsis_data"),
    path("api/synopsis/content", views.daily_synopsis_content, name="daily_synopsis_content"),
    path("api/synopsis/rerun", views.daily_synopsis_rerun, name="daily_synopsis_rerun"),
    path("assessment/", views.assessment_page, name="assessment"),
    path("api/assessment/dates", views.api_assessment_dates, name="api_assessment_dates"),
    path("api/assessment/content", views.api_assessment_content, name="api_assessment_content"),
    path("api/assessment/rerun", views.api_assessment_rerun, name="api_assessment_rerun"),
    path("api/assessment/dashboard", views.api_assessment_dashboard, name="api_assessment_dashboard"),
    path("git/", views.git_activity, name="git_activity"),
    path("api/git/data", views.git_activity_data, name="git_activity_data"),
    path("dev/", views.dev_activity, name="dev_activity"),
    path("api/dev/data", views.dev_activity_data, name="dev_activity_data"),
    path("agent-log/", views.agent_log, name="agent_log"),
    path("api/agent-log", views.agent_log_data, name="agent_log_data"),
    path("agent-queue/", views.agent_queue, name="agent_queue"),
    path("api/agent-queue/data", views.api_agent_queue_data, name="api_agent_queue_data"),
    path("research/", views.research_page, name="research"),
    path("api/research/data", views.api_research_data, name="api_research_data"),
    path("api/research/run", views.api_research_run, name="api_research_run"),
    path("api/research/stop", views.api_research_stop, name="api_research_stop"),
    path("api/research/abort", views.api_research_abort, name="api_research_abort"),
    path("api/research/rerun", views.api_research_rerun, name="api_research_rerun"),
    path("api/research/rerun-models", views.api_research_rerun_models, name="api_research_rerun_models"),
    path("research/studies/", views.research_studies, name="research_studies"),
    path("api/research/studies", views.api_research_studies, name="api_research_studies"),
    path("goals/", views.goals_page, name="goals"),
    path("api/goals/data", views.api_goals_data, name="api_goals_data"),
    path("api/goals/detail", views.api_goals_detail, name="api_goals_detail"),
    path("api/goals/create", views.api_goals_create, name="api_goals_create"),
    path("api/goals/relate", views.api_goals_relate, name="api_goals_relate"),
    path("api/goals/unrelate", views.api_goals_unrelate, name="api_goals_unrelate"),
    path("api/goals/create-note", views.api_goal_create_note, name="api_goal_create_note"),
    path("picks/", views.picks, name="picks"),
    path("api/picks/data", views.api_picks_data, name="api_picks_data"),
    path("api/picks/update", views.api_picks_update, name="api_picks_update"),
    path("api/picks/archive-run", views.api_picks_archive_run, name="api_picks_archive_run"),
    path("api/picks/run", views.api_picks_run, name="api_picks_run"),
    path("api/picks/abort", views.api_picks_abort, name="api_picks_abort"),
    path("rss/", views.rss_page, name="rss"),
    path("api/rss/data", views.api_rss_data, name="api_rss_data"),
    path("api/rss/mark-read", views.api_rss_mark_read, name="api_rss_mark_read"),
    path("api/rss/mark-item-read", views.api_rss_mark_item_read, name="api_rss_mark_item_read"),
    path("api/rss/mark-guids-read", views.api_rss_mark_guids_read, name="api_rss_mark_guids_read"),
    path("api/rss/mark-all-read", views.api_rss_mark_all_read, name="api_rss_mark_all_read"),
    path("api/rss/readme", views.api_rss_readme, name="api_rss_readme"),
    path("api/rss/fetch", views.api_rss_fetch, name="api_rss_fetch"),
    path("api/rss/add-source", views.api_rss_add_source, name="api_rss_add_source"),
    path("readme/", views.readme_page, name="readme"),
    path("api/readme/data", views.api_readme_data, name="api_readme_data"),
    path("api/readme/dismiss", views.api_readme_dismiss, name="api_readme_dismiss"),
    path("system/", views.system_health, name="system_health"),
    path("api/system/status", views.api_system_status, name="api_system_status"),
    path("api/system/data", views.api_system_data, name="api_system_data"),
    path("api/system/refresh", views.api_system_refresh, name="api_system_refresh"),
    path("api/entry/<uuid:entry_id>/save", views.api_entry_save, name="api_entry_save"),
    path("api/entry/<uuid:entry_id>/purge-versions", views.api_entry_purge_versions, name="api_entry_purge_versions"),
    path("api/entry/<uuid:entry_id>/tag/<str:tag_name>/delete", views.api_entry_tag_delete, name="api_entry_tag_delete"),
    path("api/set-public", views.api_set_public, name="api_set_public"),
    # Public pages (no auth) — context route before <path:> catch-all
    path("p/context/<str:context_name>/", views.public_context_entries, name="public_context_entries"),
    path("p/<path:entry_id>/json/", views.entry_public_json, name="entry_public_json"),
    path("p/<path:entry_id>/", views.entry_public, name="entry_public"),
    # Relate-to picker (new tab from entry edit panel)
    path("relate/<uuid:entry_uuid>/", views.relate_to_view, name="relate_to"),
    # Internal entry pages (auth required)
    path("entry/", views.entry_detail, name="entry_detail_query"),
    path("entry/<path:entry_id>/", views.entry_detail, name="entry_detail"),
    # Workday/workweek get-or-create — idempotent, redirects to entry detail
    path("workday/<str:yyyymmdd>/", views.workday_open, name="workday_open"),
    path("workweek/<str:yyyymmdd>/", views.workweek_open, name="workweek_open"),
    # This week — Sat-Fri current-week diary digest
    path("this-week/", views.this_week, name="this_week"),
    # Weekly — index of all workweek_<yyyymmdd> entries
    path("weekly/", views.weekly, name="weekly"),
    path("context/<str:context_name>/", views.context_entries, name="context_entries"),
    path("poetry/author/<path:author_name>/", views.poetry_author_entries, name="poetry_author_entries"),
    path("tag/<str:tag_name>/", views.tag_entries, name="tag_entries"),
    path("kind/<str:kind_name>/", views.kind_entries, name="kind_entries"),
    # Telegram Mini App
    path("m/", views.miniapp, name="miniapp"),
    path("api/tg-auth", views.tg_auth, name="tg_auth"),
    path("api/contexts", views.api_contexts_list, name="api_contexts_list"),
    path("api/context/<str:context_name>/entries", views.api_context_entries, name="api_context_entries"),
    path("api/entry/<uuid:entry_id>/content", views.api_entry_content, name="api_entry_content"),
]
